### PR TITLE
Configure coveralls in Ci

### LINKED ISSUE #568: Remove unnecessary files from coveralls.
Not all files need to be covered on coveralls. Files not required in coveralls are: 

- [ ] accounts/accountUtils.go
- [ ] cmd/root.go
- [ ] cmd/struct-utils.go
- [ ] path/mocks
- [ ] utils/struct-utils.go

### PR DESCRIPTION
**Pull request by Shrikant1212**
# Description

Updated CircleCI to remove unnecessary files form [coveralls.io](https://coveralls.io/) report

Fixes #568

### CODE REVIEW

**Comment by Shrikant1212** [comment]
@ashish10677  can verify changes https://coveralls.io/jobs/94493713

**Comment by SkandaBhat** [comment]
This is a crude way of solving the problem we are facing. Please explore 

https://github.com/golang/go/issues/31280

Seems like Courtney could help us achieve exclusion (or exhaustive testing) all the while enforcing 100% coverage for the files we want.
https://github.com/dave/courtney

**Comment by Shrikant1212** [comment]
@SkandaBhat  @ashish10677  can verify the output of courtney
https://coveralls.io/jobs/94541317

**Comment by SkandaBhat** [comment]
make PR to main

**Comment by Shrikant1212** [comment]
@SkandaBhat  Seems like with courtney we can only specify directory to run covegare, but our goal is to ignore few files, so we need to move ignoring files to specific directory then courtney will be helpful for us.

**Pull request closed without merging**
