### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ashish10677**
# Description
Changes in this PR
* Increase test coverage.
* Increment gasLimit while confirming block
* Fixed `GetNumberOfStakers()` function
* Fixed hashing issue in `getElectedProposer()` and added tests.
* Added dispute of wrong biggest influencer id.
* Integration of sentry.
* Added new feature to increase gas limit returned by `EstimateGas()`.
* Introduced crash recovery after commit is done.
* New retry mechanism added.
* Bug fixes.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Contracts version:
* Hardware:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by SkandaBhat** [comment]
@ashish10677 can you please add a succinct summary of the changes that are included in this PR?

**Comment by ashish10677** [comment]
> @ashish10677 can you please add a succinct summary of the changes that are included in this PR?

Done

**Comment by SkandaBhat** [comment]
There are conflicts @ashish10677

**Comment by ashish-hashstack** [comment]
> There are conflicts @ashish10677

Yeah it's still not ready for merge.

**Comment by ashish10677** [comment]
> There are conflicts @ashish10677

Yeah this is still not ready for merge.

**Pull request merged**
