### PR TITLE
Optimization for RPC calls in vote.go

### LINKED ISSUE #49: Figure out how to reduce RPC calls
# Rationale

We ping the blockchain too many times during voting just to check whether the correct state has arrived or not. Rather than doing that, it'll be better if we calculate the timing of the next state and ping at that particular moment.

# Implementation

Since we know the state length, epoch length, and approximate time to mine a block on a particular blockchain, we can calculate the approximate time when the next state will occur.

### PR DESCRIPTION
**Pull request by ashish10677**
Currently, we fetch a block every 3 secs while voting. This increases the number of RPC calls and is not feasible. Instead of doing that, this fix aims at fetching the block once in every state.  This will reduce the number of RPC calls drastically and optimise the voting process.

Closes #49

### CODE REVIEW

**Comment by hrishikeshio** [comment]
Once in every state is too risky. What if block time is slightly reduced/increased due to unknown reasons? Once every `blocktime` should be reasonable.

**Comment by ashish10677** [comment]
> Once in every state is too risky. What if block time is slightly reduced/increased due to unknown reasons? Once every `blocktime` should be reasonable.

@hrishikeshio to avoid this issue, we are pinging 10 blocks before a new state, this way we minimize the risk.

**Comment by hrishikeshio** [comment]
> > Once in every state is too risky. What if block time is slightly reduced/increased due to unknown reasons? Once every `blocktime` should be reasonable.
> 
> @hrishikeshio to avoid this issue, we are pinging 10 blocks before a new state, this way we minimize the risk.

still not worth the risk. pinging once every 1 block doesn't sound unreasonable.

**Comment by ashish10677** [comment]
> > > Once in every state is too risky. What if block time is slightly reduced/increased due to unknown reasons? Once every `blocktime` should be reasonable.
> > 
> > 
> > @hrishikeshio to avoid this issue, we are pinging 10 blocks before a new state, this way we minimize the risk.
> 
> still not worth the risk. pinging once every 1 block doesn't sound unreasonable.
> can we make it a configurable parameter?

The only problem in pinging every block is that there are too many requests made, and that might go beyond the Infura limit as in Matic, a block is mined every 2-3 seconds. So in a minute, there will be 20-30 requests, just to check the state.

**Comment by SkandaBhat** [comment]
Makes sense to have it configurable. I might want to play around with RPC call frequency to optimise my rewards after paying out infura/quicknode etc.

**Comment by ashish10677** [comment]
I'll be sending a new PR with a configurable wait time for the next state.

**Pull request closed without merging**
