### PR TITLE
jobList command added

### LINKED ISSUE #36: Getter function for Job List
# Rationale

This feature is required for the admin as well as the user to view the list of jobs and their various properties that are available in the structs contract.

# Implementation

Implementation would be similar to #35

### PR DESCRIPTION
**Pull request by shekhar2807**
# Description

jobList command added.
It returns details like weight, power, Id etc of all the jobs.

Fixes #36

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test 1: When jobList executes properly
- [x] Test 2: When there is a error fetching job list

**Test Configuration**:
* Contracts version: v0.1.76
* Hardware: Macbook M1 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ashish10677** [comment]
@shekhar2807 can you pull the latest changes in develop and push again so that the tests pass.

**Comment by ashish10677** [comment]
@shekhar2807 please add tests. Coverage has gone down.

**Review by ashish10677 — APPROVED** [review]
lgtm

**Review by Yashk767 — APPROVED** [review]
LGTM

**Pull request merged**
