### PR TITLE
Configure binary build

### PR DESCRIPTION
**Pull request by Shrikant1212**
# Description

This include Circle-CI update for creating amd and arm builds and push to github artifacts along with install script for configuring binary on linux host 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
Running stakers from 4-5 days, all working as expected

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ashish10677** [comment]
@Shrikant1212 tests are failing.

**Comment by Shrikant1212** [comment]
@ashish10677  can you re-run CI, this is because it's using different Circle-CI account

**Comment by ashish10677** [comment]
The rerun option is disabled for me.
image

@SkandaBhat can you please help.

**Comment by Shrikant1212** [comment]
@ashish10677  can you please check again, I've re run the CI?

**Comment by ashish10677** [comment]
> @ashish10677 can you please check again, I've re run the CI?

Yeah it passes. I'll review.

**Pull request merged**
