### PR TITLE
Add docker support.

### LINKED ISSUE #57: Dockerise razor-go
# Rationale
There are lot of environment specific nuances that could surface problems with razor-go operation.

# Implementation
Dockerise the node so that we have control over dependencies and environment.

### PR DESCRIPTION
**Pull request by SkandaBhat**
I have updated geth version as well, since the ethereum/client-go was having issues. fixes #57

### CODE REVIEW

**Review by ashish10677 — APPROVED** [review]
Works as expected for me.

**Comment by hrishikeshio** [comment]
How to build?

**Comment by ashish10677** [comment]
> How to build?

It is not yet merged to the main branch.

You can checkout to add-dockerfile branch and run `docker build .` to build the docker image.
Then run
```
docker run -it <image_name> /bin/bash  
```

**Comment by ashish10677** [comment]
@SkandaBhat can you update the README as well before merging?

**Pull request merged**
