### PR TITLE
Test utils/stake.go

### LINKED ISSUE #521: Add tests for utils/stake.go

### PR DESCRIPTION
**Pull request by shekhar2807**
-added tests for utils/stake.go
-fixes #521

### CODE REVIEW

**Comment by ashish10677** [comment]
@shekhar2807 please resolve the conflicts

**Comment by shekhar2807** [comment]
> @shekhar2807 please resolve the conflicts

Done @ashish10677.

**Comment by ashish10677** [comment]
New conflicts are generated @shekhar2807

**Comment by shekhar2807** [comment]
> New conflicts are generated @shekhar2807

Done @ashish10677 but the build is failing due to some installation error.

**Comment by ashish10677** [comment]
@shekhar2807 conflicts again.

**Review by ashish10677 — APPROVED** [review]

**Pull request merged**
