### PR TITLE
Test delegate

### LINKED ISSUE #199: Tests for delegate command

### PR DESCRIPTION
**Pull request by Yashk767**
Closes #199

### CODE REVIEW

**Comment by ashish10677** [comment]
Shouldn't flag testing be done here as well? What do you think @Yashk767 ?

**Comment by Yashk767** [comment]
> Shouldn't flag testing be done here as well? What do you think @Yashk767 ?

Actually we are calling approve function before delegate , so here we need the flag inputs for txnArgs in both approve and delegate as well.

**Comment by Yashk767** [comment]
> Shouldn't flag testing be done here as well? What do you think @Yashk767 ?

We can do one thing, we can include approve function call inside delegate and stakeCoins function along with flags and create a CmdInterface and implement functions like approve in it, as it is being used as dependent function so that we can call it from there and get the flags tested as well

**Comment by ashish10677** [comment]
> > Shouldn't flag testing be done here as well? What do you think @Yashk767 ?
> 
> Actually we are calling approve function before delegate , so here we need the flag inputs for txnArgs in both approve and delegate as well.

Ok, so in approve the flags are being tested right?

**Comment by Yashk767** [comment]
> > > Shouldn't flag testing be done here as well? What do you think @Yashk767 ?
> > 
> > 
> > Actually we are calling approve function before delegate , so here we need the flag inputs for txnArgs in both approve and delegate as well.
> 
> Ok, so in approve the flags are being tested right?

At current they are not,  but we can include flags in approve itself and test them there, and extra flag like stakerId in delegate can be included in delegate function itself.  We need to implement flag functions and use them accordingly which I have done for other PR so can we modify approve and do this in some other PR ?

**Comment by ashish10677** [comment]
> At current they are not, but we can include flags in approve itself and test them there, and extra flag like stakerId in delegate can be included in delegate function itself. We need to implement flag functions and use them accordingly which I have done for other PR so can we modify approve later and do this in some other PR ?

Yes

**Comment by ashish10677** [comment]
Also fix the conflicts @Yashk767

**Review by ashish10677 — APPROVED** [review]

**Pull request merged**
