### PR TITLE
Added benchmarks for getIteration

### LINKED ISSUE #551: Add benchmark for getIteration method

### PR DESCRIPTION
**Pull request by Yashk767**
# Description

Added benchmarks for getIteration()

Fixes #551

### CODE REVIEW

**Comment by Yashk767** [comment]
- All tests gets passed successfully on running command `go test ./...` 
- But when trying to run benchmarks along with tests using command `go test ./... -bench=.` , tests fail with benchmarks function throwing error.
- On running tests with command `go test ./... -bench=.  -run=^#` which executes benchmarks only and ignores tests execution results in successful execution of benchmarks.

@SkandaBhat  @ashish10677

**Comment by Yashk767** [comment]
Benchmark output -

```{"CPUs":8,"Core":"5.13.0-28-generic","Operating System":"GNU/Linux","Platform":"x86_64","go version":"go1.17rc2","level":"info","msg":"","razor-go version":"0.2.0-stable","time":"2022-02-16T13:19:23+05:30"}
goos: linux
goarch: amd64
pkg: razor/cmd
cpu: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
BenchmarkGetIteration/Stakers_Stake_1000-8                     1        3259085965 ns/op
BenchmarkGetIteration/Stakers_Stake_10000-8                    5         217270641 ns/op
BenchmarkGetIteration/Stakers_Stake_100000-8                  16          69583788 ns/op
BenchmarkGetIteration/Stakers_Stake_1000000-8                496           2299130 ns/op
BenchmarkGetIteration/Stakers_Stake_10000000-8              4680            278617 ns/op
PASS
ok      razor/cmd       9.343s
```

**Comment by SkandaBhat** [comment]
@Yashk767 can you also put the failure output here?
cc: @Shrikant1212 can you please look into why this could be happening?

**Comment by Shrikant1212** [comment]
@ashish10677 It's fixed, please help in reviewing

**Review by ashish10677 — APPROVED** [review]
LGTM

**Pull request merged**
