### PR TITLE
Replacing path.join with filepath.join

### LINKED ISSUE #884: Use `filepath.join` instead of `path.join`
`path.Join(...)` always joins using a forward slash. This may cause issues in windows or other systems using a different delimiter. Use `filepath.Join(...)` instead which uses os specific path separators.

This has to be done in:
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/create.go#L47
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/import.go#L56
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/listAccounts.go#L45
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/cmd/vote.go#L315
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L16
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L32
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L40
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L55
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L64
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L82
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L98
- [ ] https://github.com/razor-network/razor-go/blob/8051af8424e1da3b26f00439b640b8562c7338e9/path/path.go#L114

### PR DESCRIPTION
**Pull request by Handschrift**
# Description

Copy of: #886 

Changed different occurrences of path.join to filepath.join for using os specific path seperators.

There are more occurrences than mentioned in the issue. I hope that it is okay if I replaced every occurrence in the stated files.

Fixes #884 

## Type of change

Please delete options that are not relevant.

- [x] code cleanup

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit-Testing
- [x] IDE static code analysis
- [x] checking for passing build

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ashish10677 — APPROVED** [review]

**Review by shekhar2807 — COMMENTED** [review]
In my opinion it would be better if we merge this to v1-audit branch. 
cc: @ashish10677 @Yashk767

**Comment by ashish10677** [comment]
> In my opinion it would be better if we merge this to v1-audit branch. cc: @ashish10677 @Yashk767

We'll merge this, once v1-audit is merged with main. So, should not be any issues there.

**Review by shekhar2807 — DISMISSED** [review]

**Comment by ashish10677** [comment]
@Handschrift can you please resolve the conflicts?
Note that the file names like "logs", "razor.yaml", etc have been moved to constants and those constants will now be used.

**Comment by Handschrift** [comment]
I resolved the merge conflicts and now the new constants are used as well.

**Review by shekhar2807 — DISMISSED** [review]

**Review by ashish10677 — APPROVED** [review]
Lgtm

**Comment by ashish10677** [comment]
@Handschrift I cannot merge this because the commits aren't signed. Can you please sign your commits?
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
image

**Comment by Handschrift** [comment]
Yep, I am on it

**Pull request closed without merging**
